name: Black Pearl
favicon: null
layout_spectrum: 0.90644
typography_spectrum: 0.36291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#e0cecd'
    - '#0e3d64'
    - '#b3aaa8'
    - '#456f85'
  brandStrength: 0.4375
  lightness: 0.32517083501443267
  saturation: 0.8613452347926795
  rhythmicContrast: 0.4183171931654215
purpose: []
