name: Black Pearl
favicon: null
layout_spectrum: 0.9642843992915004
typography_spectrum: 0.48237454635091126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44849127111956477
  lightness: 0.32517083501443267
  saturation: 0.8613452347926795
  rhythmicContrast: 0.4183171931654215
purpose: []
